spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  #main:
  #  banner-mode: off
selenium:
  chrome-driver-location: "/usr/src/app/chromedriver"
  testUrl: "https://google.com"
aws:
  sqsUrl: "https://sqs.eu-central-1.amazonaws.com/397254617684/crawler_queue"
  credentialsFile: "config/aws.json"
figshare:
  queryUrl: "https://figshare.com/search?q=xtc%E2%80%8B%2C%20%E2%80%8Bdcd%2C%E2%80%8B%20%E2%80%8Bntraj%2C%20netcdf%2C%20trr%2C%20lammpstrj%2C%20xyz%2C%20binpos%2C%20hdf5%2C%20dtr%2C%20arc%2C%20tng%2C%20mdcrd%2C%20crd%2C%20dms%2C%20trj%2C%20ent%2C%20ncdf"
  fetchLimit: 10
mendeley:
  queryUrl: "https://data.mendeley.com/api/research-data/search?search=molecular%20trajectories&type=DATASET&page=%s"
